### ISSUE TITLE
JobDriver FinishRecipeAndStartStoringProduct

### ISSUE THREAD

**Issue by MrXarous** [emipa606/LessArbitrarySurgery#2]
Multiple users reported that there were some kind of problems on the mod's page, but no logs or pertinent data. When user Meelock came into the Discord reporting an issue soon discovered whatever was happening was blowing up his player.log to almost 30GB. I went ahead and did a testing environment with just Harmony/Core/DLCs/Hugslib/LessArbitrarySurgery.

Dev spawned hospital bed and did a bill for an operation to harvest pawn's right lung when complete JobDriver threw error and the surgery would be repeated endlessly. Pawn doing the surgery would get xp and made sure there was a stockpile capable to handle the product. Still threw error.

https://gist.github.com/a82e00492ed3422afc316d6e227bff77

**Comment by emipa606** [comment]
FIxed in d150a03
